Training on device cuda:0
Traceback (most recent call last):
  File "/home/zuern/Pycharm/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/zuern/Pycharm/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/zuern/Pycharm/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/zuern/Pycharm/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 294, in <module>
    main()
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 55, in main
    model = TrackerSiamFC(modality=args.modality)
  File "/home/zuern/SiamRPN-PyTorch/train/net.py", line 153, in __init__
    head=SiamFC(self.config['out_scale']))
AttributeError: 'TrackerSiamFC' object has no attribute 'config'
Backend TkAgg is interactive backend. Turning interactive mode on.
We've got an error while stopping in post-mortem: <class 'KeyboardInterrupt'>

